(function(){
'use strict';
const $=s=>document.querySelector(s);
let token=null,user=null;
function msg(t,ok){const e=$('#message');e.textContent=t;e.className=ok?'success':'error';}
function cfg(){if(!window.YARA_CONFIG)throw Error('فایل config.js پیدا نشد.');const u=window.YARA_CONFIG.SUPABASE_URL,k=window.YARA_CONFIG.SUPABASE_ANON_KEY;if(!u||u.includes('YOUR-')||!k||k.includes('YOUR_'))throw Error('اطلاعات Supabase در config.js کامل نیست.');return {u:u.replace(/\/$/,''),k:k};}
async function api(path,opt){const c=cfg();const r=await fetch(c.u+path,Object.assign({headers:{apikey:c.k,Authorization:'Bearer '+(token||c.k),'Content-Type':'application/json'}},opt||{}));let d=null;try{d=await r.json()}catch(_){ }if(!r.ok)throw Error((d&&((d.msg)||(d.message)||(d.error_description)||(d.error)))||('خطای سرور '+r.status));return d;}
async function login(){const email=$('#email').value.trim(),password=$('#password').value;if(!email||!password)return msg('ایمیل و رمز عبور را وارد کنید.',false);const b=$('#signin');b.disabled=true;b.textContent='در حال ورود...';try{const c=cfg();const r=await fetch(c.u+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:c.k,'Content-Type':'application/json'},body:JSON.stringify({email,password})});let d={};try{d=await r.json()}catch(_){}if(!r.ok)throw Error(d.error_description||d.msg||d.message||'ایمیل یا رمز عبور نادرست است.');token=d.access_token;user=d.user;if(!token||!user)throw Error('ورود انجام نشد.');const rows=await api('/rest/v1/profiles?id=eq.'+encodeURIComponent(user.id)+'&select=role');if(!rows||!rows.length||rows[0].role!=='admin'){token=null;user=null;throw Error('این حساب در profiles نقش admin ندارد.');}$('#login').hidden=true;$('#panel').hidden=false;$('#logout').hidden=false;$('#welcome').textContent='ورود مدیر با موفقیت انجام شد.';msg('',true);await load();}catch(e){msg(e.message||String(e),false);}finally{b.disabled=false;b.textContent='ورود';}}
async function load(){try{const ps=await api('/rest/v1/products?is_active=eq.true&select=id,name,price,category&order=created_at.desc');const os=await api('/rest/v1/orders?select=id&order=created_at.desc');$('#productCount').textContent=(ps||[]).length.toLocaleString('fa-IR');$('#orderCount').textContent=(os||[]).length.toLocaleString('fa-IR');$('#products').innerHTML=ps&&ps.length?ps.map(p=>'<div class="item"><span>'+esc(p.name)+' — '+Number(p.price||0).toLocaleString('fa-IR')+' تومان</span></div>').join(''):'<p>محصول فعالی ثبت نشده است.</p>';}catch(e){msg('ورود انجام شد، اما دریافت اطلاعات با خطا روبه‌رو شد: '+(e.message||e),false);}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
$('#signin').addEventListener('click',login);$('#password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#logout').addEventListener('click',()=>{token=null;user=null;$('#panel').hidden=true;$('#logout').hidden=true;$('#login').hidden=false;$('#password').value='';});
try{cfg();}catch(e){msg(e.message,false)}
})();
